SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS D
JOIN(
    SELECT CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
    ) AS F
ON (D.SKILL_CODE & F.CODE) = F.CODE
ORDER BY D.ID ASC;