# 부서별 평균 연봉 조회하려고 함.
# 평균 연봉 : 첫째자리에서 반올림 & AVG_SAL
# HR_DEPARTMENT : 회사의 부서 정보를 담은 테이블
# HR_EMPLOYEES : 회사 사원 정보를 담은 테이블

SELECT D.DEPT_ID, D.DEPT_NAME_EN,
        ROUND(AVG(E.SAL)) AS AVG_SAL
FROM HR_EMPLOYEES E
JOIN HR_DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID
GROUP BY  D.DEPT_ID, D.DEPT_NAME_EN
ORDER BY AVG_SAL DESC
